//------------------------------------------------------------------------------
// <auto-generated>
//     Este c�digo fue generado por una herramienta.
//     Versi�n del motor en tiempo de ejecuci�n:2.0.50727.3603
//
//     Los cambios en este archivo podr�an causar un comportamiento incorrecto y se perder�n si
//     se vuelve a generar el c�digo.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juleweb.portal.portada {
    
    
    /// <summary>
    /// Clase portada.
    /// </summary>
    /// <remarks>
    /// Clase generada autom�ticamente.
    /// </remarks>
    public partial class portada {
        
        /// <summary>
        /// Control hplInicio.
        /// </summary>
        /// <remarks>
        /// Campo generado autom�ticamente.
        /// Para modificar, mueva la declaraci�n del campo del archivo del dise�ador al archivo de c�digo subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink hplInicio;
    }
}
