Hello, $table.name$ 


asd
dsf

asdf
asdf
f


fasd

asdf
f
asdf

asdf


                xx$table.fields.Count$ 
                <ul>
                $table.fields:{<li>$it.name$</li>}$
                </ul>

				
				using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Text;
using System.IO;
using System.Data;
using System.Web;
using System.ComponentModel;


[System.ComponentModel.DataObject]
public partial class $table.name$Bll
{
 
 
 $table.name$ xx$table.fields.Count$ 