<#-- variables used internally by the generator... -->
<#assign nameFile="ficha_${table}">
<#assign extensionFile="aspx.designer.cs">
<#assign languageGenerated="c#">
<#assign description="c#">
<#assign targetDirectory="main_${table}">
<#assign appliesToAllTables="true">
<#-- END variables used internally by the generator... -->
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3082
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ${project}.portal.main_${table} {
    
    
    /// <summary>
    /// Clase ficha_${table}.
    /// </summary>
    /// <remarks>
    /// Clase generada automáticamente.
    /// </remarks>
    public partial class ficha_${table} {
        
		#set ($count = 0)
#foreach( $field in $table.GetArrayOfFields )
  #if (!$field.isKey())

   
     
     
              #if ($field.type.toString() == "_integer")
                
				/// <summary>
				/// Control lab${field}.
				/// </summary>
				/// <remarks>
				/// Campo generado automaticamente.
				/// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
				/// </remarks>
				protected global::System.Web.UI.WebControls.Label lab${field};       
                
                 #end 
              #if ($field.type.toString() == "_string")
                   /// <summary>
                    /// Control lab${field}.
                    /// </summary>
                    /// <remarks>
                    /// Campo generado automaticamente.
                    /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                    /// </remarks>
                    protected global::System.Web.UI.WebControls.Label lab${field};
                 #end 
              #if ($field.type.toString() == "_date")
                   /// <summary>
                    /// Control lab${field}.
                    /// </summary>
                    /// <remarks>
                    /// Campo generado automaticamente.
                    /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                    /// </remarks>
                    protected global::System.Web.UI.WebControls.Label lab${field};
                 #end 
              #if ($field.type.toString() == "_boolean")
                   /// <summary>
                    /// Control ck${field}.
                    /// </summary>
                    /// <remarks>
                    /// Campo generado automáticamente.
                    /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                    /// </remarks>
                    protected global::System.Web.UI.WebControls.CheckBox ck${field};
                 #end 
              #if ($field.type.toString() == "_image")
                   /// <summary>
                    /// Control img${field}.
                    /// </summary>
                    /// <remarks>
                    /// Campo generado automáticamente.
                    /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                    /// </remarks>
                    protected global::System.Web.UI.WebControls.Image  img${field};
					
					/// <summary>
					/// Control lblInfo${field}.
					/// </summary>
					/// <remarks>
					/// Campo generado automaticamente.
					/// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
					/// </remarks>
					protected global::System.Web.UI.WebControls.Label lblInfo${field};       
               
					
                 #end 
              <#default>
                    /// <summary>
                    /// Control lab${field}.
                    /// </summary>
                    /// <remarks>
                    /// Campo generado automaticamente.
                    /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                    /// </remarks>
                    protected global::System.Web.UI.WebControls.Label lab${field};
      
    #set ($count = $count + 1 )
 #end
#end 
		
 
      
        
      
           
      
        
      
        
         
        
        /// <summary>
        /// Control hplMantenimiento.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink hplMantenimiento;
        
         
    }
}
